apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DATABASE_URL_TEMPLATE: 'postgresql+asyncpg://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}'

  ALGORITHM: 'HS256'
  ACCESS_TOKEN_EXPIRE_MINUTES: '30'
  API_BASE_URL: 'http://api-service:8000'
  BASE_URL: 'http://links.local/'
  IS_IN_DOCKER: '1'
  REDIS_URL: 'redis://redis-service:6379/0'
  POSTGRES_DB: 'sldb'