apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:

      containers:
      - name: migration-container
        image: varenikvkusny/link-simplifier:1.0
        command: ["alembic",  "upgrade", "head"]

        envFrom:

        - configMapRef:
            name: app-config

        env:
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        
        - name: POSTGRES_DB
          value: 'sldb'
        
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SECRET_KEY

      restartPolicy: Never

  backoffLimit: 4