apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: link-simplifier
spec:
  replicas: 2

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api-container

          image: varenikvkusny/link-simplifier:1.3

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"

          envFrom:
            - configMapRef:
                name: app-config

          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY

            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BOT_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: link-simplifier
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
