"""Deleted short link column and added click_count column to Link model

Revision ID: 105b2571bfa6
Revises: 348da507d6b3
Create Date: 2025-08-09 14:19:09.906235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105b2571bfa6'
down_revision: Union[str, Sequence[str], None] = '348da507d6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('click_count', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_links_short_link'), table_name='links')
    op.drop_column('links', 'short_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('short_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_links_short_link'), 'links', ['short_link'], unique=True)
    op.drop_column('links', 'click_count')
    # ### end Alembic commands ###
