"""Delete some indexes

Revision ID: 9e713a4251ed
Revises: ff53ab01da26
Create Date: 2025-08-19 14:03:12.736240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e713a4251ed'
down_revision: Union[str, Sequence[str], None] = 'ff53ab01da26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_original_link'), table_name='links')
    op.drop_index(op.f('ix_users_password_hash'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_password_hash'), 'users', ['password_hash'], unique=False)
    op.create_index(op.f('ix_links_original_link'), 'links', ['original_link'], unique=False)
    # ### end Alembic commands ###
