name: Run Python Tests

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis:8-alpine

                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

                ports:
                    - 6379:6379

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4

            - name: Install requirements
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Start tests

              env:
                  TEST_REDIS_HOST: redis
              run: pytest